//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int accno { get; set; }
        public string memId { get; set; }
        public string bank { get; set; }
        public string cardType { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
