//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string memId { get; set; }
        public string activityCode { get; set; }
        public System.DateTime sessionDate { get; set; }
        public Nullable<int> satisfaction { get; set; }
        public Nullable<int> usage { get; set; }
        public int id { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Member Member { get; set; }
    }
}
